import smtplib
from email.mime.text import MIMEText


def send_prediction_email(receiver, symbol, prediction, analysis):

    sender = "yourgmail@gmail.com"
    password = "your_app_password"

    subject = f"AlphaAnalytics Prediction for {symbol}"

    body = f"""
Stock Prediction Report

Symbol: {symbol}

Predicted Prices

Open: {prediction['open']}
High: {prediction['high']}
Low: {prediction['low']}
Close: {prediction['close']}

AI Analysis:
{analysis}

Generated by AlphaAnalytics AI
"""

    msg = MIMEText(body)

    msg["Subject"] = subject
    msg["From"] = sender
    msg["To"] = receiver

    server = smtplib.SMTP("smtp.gmail.com", 587)
    server.starttls()

    server.login(sender, password)

    server.sendmail(sender, receiver, msg.as_string())

    server.quit()