# email_service.py
import os
import logging
import threading
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail

# Set up logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

def send_prediction_email(recipient_email, symbol, predictions, analysis):
    """
    Send prediction results via email using SendGrid (non-blocking)
    Returns immediately, sends email in background thread
    """
    def _send_email_task():
        """Background task to actually send the email"""
        try:
            # Get SendGrid API key from environment
            sendgrid_api_key = os.getenv("SENDGRID_API_KEY")
            from_email = os.getenv("EMAIL_SENDER", "razilchristian@gmail.com")
            
            logger.info(f"📧 SendGrid task started for {symbol}")
            logger.info(f"SendGrid API Key configured: {'Yes' if sendgrid_api_key else 'No'}")
            
            if not sendgrid_api_key:
                logger.error("❌ SendGrid API key not configured")
                return False
            
            # Create HTML content
            html_content = f"""
            <html>
            <body style="font-family: Arial, sans-serif; padding: 20px; max-width: 600px;">
                <div style="background: linear-gradient(135deg, #6366f1 0%, #8b5cf6 100%); color: white; padding: 20px; border-radius: 10px 10px 0 0;">
                    <h2 style="margin: 0;">🚀 AlphaAnalytics AI Prediction</h2>
                </div>
                <div style="background: #f9fafb; padding: 20px; border: 1px solid #e5e7eb; border-top: none; border-radius: 0 0 10px 10px;">
                    <h3 style="color: #6366f1; margin-top: 0;">{symbol}</h3>
                    
                    <h4>📊 Price Predictions</h4>
                    <table style="width: 100%; border-collapse: collapse;">
                        <tr style="border-bottom: 1px solid #e5e7eb;">
                            <td style="padding: 8px 0;"><b>Open:</b></td>
                            <td style="padding: 8px 0;">${predictions['open']['value']}</td>
                            <td style="padding: 8px 0; color: #6b7280;">({predictions['open']['confidence']}%)</td>
                        </tr>
                        <tr style="border-bottom: 1px solid #e5e7eb;">
                            <td style="padding: 8px 0;"><b>High:</b></td>
                            <td style="padding: 8px 0;">${predictions['high']['value']}</td>
                            <td style="padding: 8px 0; color: #6b7280;">({predictions['high']['confidence']}%)</td>
                        </tr>
                        <tr style="border-bottom: 1px solid #e5e7eb;">
                            <td style="padding: 8px 0;"><b>Low:</b></td>
                            <td style="padding: 8px 0;">${predictions['low']['value']}</td>
                            <td style="padding: 8px 0; color: #6b7280;">({predictions['low']['confidence']}%)</td>
                        </tr>
                        <tr>
                            <td style="padding: 8px 0;"><b>Close:</b></td>
                            <td style="padding: 8px 0;">${predictions['close']['value']}</td>
                            <td style="padding: 8px 0; color: #6b7280;">({predictions['close']['confidence']}%)</td>
                        </tr>
                    </table>
                    
                    <h4>📈 Trend Analysis</h4>
                    <p><b>Trend:</b> {predictions.get('trend', 'NEUTRAL')} ({predictions.get('trend_strength', 50)}%)</p>
                    <p><b>Recommendation:</b> 
                        <span style="color: {'#10b981' if predictions.get('recommendation') in ['BUY', 'STRONG BUY'] else '#ef4444' if predictions.get('recommendation') in ['SELL', 'STRONG SELL'] else '#f59e0b'}; font-weight: bold;">
                            {predictions.get('recommendation', 'HOLD')}
                        </span>
                    </p>
                    
                    <h4>🤖 AI Analysis</h4>
                    <p style="background: white; padding: 15px; border-radius: 5px; font-style: italic;">"{analysis}"</p>
                    
                    <hr style="border: none; border-top: 1px solid #e5e7eb; margin: 20px 0;">
                    <p style="color: #6b7280; font-size: 12px; text-align: center;">
                        Generated by AlphaAnalytics • This is an AI prediction • Always do your own research
                    </p>
                </div>
            </body>
            </html>
            """
            
            # Create plain text version
            text_content = f"""
            AlphaAnalytics AI Prediction for {symbol}
            
            PRICE PREDICTIONS:
            - Open: ${predictions['open']['value']} ({predictions['open']['confidence']}%)
            - High: ${predictions['high']['value']} ({predictions['high']['confidence']}%)
            - Low: ${predictions['low']['value']} ({predictions['low']['confidence']}%)
            - Close: ${predictions['close']['value']} ({predictions['close']['confidence']}%)
            
            TREND: {predictions.get('trend', 'NEUTRAL')} ({predictions.get('trend_strength', 50)}%)
            RECOMMENDATION: {predictions.get('recommendation', 'HOLD')}
            
            AI ANALYSIS:
            {analysis}
            
            Generated by AlphaAnalytics
            """
            
            # Create message
            message = Mail(
                from_email=from_email,
                to_emails=recipient_email,
                subject=f"🚀 AlphaAnalytics AI Report: {symbol}",
                html_content=html_content,
                plain_text_content=text_content
            )
            
            # Send via SendGrid
            logger.info(f"📡 Sending via SendGrid for {symbol}...")
            sg = SendGridAPIClient(sendgrid_api_key)
            response = sg.send(message)
            
            logger.info(f"✅ SendGrid response: {response.status_code}")
            if response.status_code in [200, 202]:
                logger.info(f"✅ Email sent successfully for {symbol}")
                return True
            else:
                logger.error(f"❌ SendGrid error: {response.status_code} - {response.body}")
                return False
            
        except Exception as e:
            logger.error(f"❌ SendGrid error: {e}")
            import traceback
            traceback.print_exc()
        return False
    
    # Start background thread
    logger.info(f"📧 Queueing email for {symbol} via SendGrid...")
    thread = threading.Thread(target=_send_email_task)
    thread.daemon = True
    thread.start()
    
    return True