# email_service.py
import smtplib
import os
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

def send_prediction_email(recipient_email, symbol, predictions, analysis):
    """
    Send prediction results via email
    """
    sender_email = os.getenv("EMAIL_SENDER")
    sender_password = os.getenv("EMAIL_PASSWORD")
    
    if not sender_email or not sender_password:
        print("Email not configured. Set EMAIL_SENDER and EMAIL_PASSWORD in .env")
        return False
    
    try:
        msg = MIMEMultipart()
        msg['From'] = sender_email
        msg['To'] = recipient_email
        msg['Subject'] = f"AlphaAnalytics AI Prediction for {symbol}"
        
        body = f"""
        <html>
        <body style="font-family: Arial, sans-serif;">
            <h2 style="color: #6366f1;">AlphaAnalytics AI Prediction</h2>
            <h3>Stock: {symbol}</h3>
            
            <h4>📊 Predictions:</h4>
            <ul>
                <li><strong>Open:</strong> ${predictions['open']['value']}</li>
                <li><strong>High:</strong> ${predictions['high']['value']}</li>
                <li><strong>Low:</strong> ${predictions['low']['value']}</li>
                <li><strong>Close:</strong> ${predictions['close']['value']}</li>
            </ul>
            
            <h4>🤖 Analysis:</h4>
            <p>{analysis}</p>
            
            <hr>
            <p style="color: #666;">Generated by AlphaAnalytics</p>
        </body>
        </html>
        """
        
        msg.attach(MIMEText(body, 'html'))
        
        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls()
        server.login(sender_email, sender_password)
        server.send_message(msg)
        server.quit()
        
        print(f"✓ Email sent to {recipient_email}")
        return True
        
    except Exception as e:
        print(f"Email error: {e}")
        return False